package mfes_shogi;
//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2013-12-07 by the VDM++ to JAVA Code Generator
// (v9.0.2 - Thu 14-Mar-2013 12:36:47 +0900)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// This file was genereted from "C:\\Users\\vitor_000\\Documents\\Overture\\workspace\\MFES_SHOGI\\classes\\Bishop.rtf".

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO
import java.util.Set;
import java.util.HashSet;
import java.util.Iterator;
import jp.vdmtools.VDM.UTIL;
import jp.vdmtools.VDM.Record;
import jp.vdmtools.VDM.Sentinel;
import jp.vdmtools.VDM.EvaluatePP;
import jp.vdmtools.VDM.CGException;
// ***** VDMTOOLS END Name=imports



public class Bishop extends Piece {


// ***** VDMTOOLS START Name=BishopSentinel KEEP=NO
  class BishopSentinel extends PieceSentinel {

    public final int Bishop = 10;

    public final int validMovement = 11;

    public final int nr_functions = 12;


    public BishopSentinel () throws CGException {}


    public BishopSentinel (EvaluatePP instance) throws CGException {
      init(nr_functions, instance);
    }

  }
// ***** VDMTOOLS END Name=BishopSentinel
;

// ***** VDMTOOLS START Name=setSentinel KEEP=NO
  public void setSentinel () {
    try {
      sentinel = new BishopSentinel(this);
    }
    catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=setSentinel


// ***** VDMTOOLS START Name=vdm_init_Bishop KEEP=NO
  private void vdm_init_Bishop () {}
// ***** VDMTOOLS END Name=vdm_init_Bishop


// ***** VDMTOOLS START Name=Bishop KEEP=NO
  public Bishop () throws CGException {
    vdm_init_Bishop();
  }
// ***** VDMTOOLS END Name=Bishop


// ***** VDMTOOLS START Name=Bishop#1|Object KEEP=NO
  public Bishop (final Object p) throws CGException {
    super(p);
    vdm_init_Bishop();
  }
// ***** VDMTOOLS END Name=Bishop#1|Object


// ***** VDMTOOLS START Name=validMovement#2|Cell|Cell KEEP=NO
  public Boolean validMovement (final Cell c1, final Cell c2) throws CGException {
    sentinel.entering(((BishopSentinel)sentinel).validMovement);
    try {
      if (promoted.booleanValue()) 
        return validKingMove(c1, c2);
      else {
        Boolean rexpr_4 = null;
        Boolean var1_5 = null;
        Boolean var1_6 = null;
        if ((var1_6 = Boolean.valueOf(Math.abs(((c1.x).intValue() - (c2.x).intValue())) == Math.abs(((c1.y).intValue() - (c2.y).intValue())))).booleanValue()) {
          boolean tmpQuant_21 = true;
          {
            Set e1_set_27 = intermediateVals((c1.x), (c2.x));
            Set e1_set_33 = intermediateVals((c1.y), (c2.y));
            Number xi = null;
            Number yi = null;
            Set tmpSet_70 = new HashSet(e1_set_33);
            for (Iterator enm_69 = tmpSet_70.iterator(); enm_69.hasNext() && tmpQuant_21; ) {
              Number elem_68 = UTIL.NumberToInt(enm_69.next());
              /* yi */
              yi = elem_68;
              Set tmpSet_67 = new HashSet(e1_set_27);
              for (Iterator enm_66 = tmpSet_67.iterator(); enm_66.hasNext() && tmpQuant_21; ) {
                Number elem_65 = UTIL.NumberToInt(enm_66.next());
                /* xi */
                xi = elem_65;
                Boolean pred_34 = null;
                if (Math.abs(((c1.x).intValue() - xi.intValue())) == Math.abs(((c1.y).intValue() - yi.intValue()))) {
                  Boolean var2_46 = null;
                  Boolean var1_47 = null;
                  Board obj_52 = Board.getInstance();
                  if (!(var1_47 = Boolean.valueOf(UTIL.equals((obj_52.getCell(xi, yi).piece), null))).booleanValue()) 
                    var1_47 = Boolean.valueOf(xi.intValue() == (c1.x).intValue());
                  if (!(var2_46 = var1_47).booleanValue()) 
                    var2_46 = Boolean.valueOf(xi.intValue() == (c2.x).intValue());
                  pred_34 = var2_46;
                }
                else 
                  pred_34 = Boolean.TRUE;
                if (!pred_34.booleanValue()) 
                  tmpQuant_21 = false;
              }
            }
          }
          var1_6 = Boolean.valueOf(tmpQuant_21);
        }
        if ((var1_5 = var1_6).booleanValue()) 
          var1_5 = notFriend(c1, c2);
        if ((rexpr_4 = var1_5).booleanValue()) 
          rexpr_4 = Boolean.valueOf(!protectingKing(c1, c2).booleanValue());
        return rexpr_4;
      }
    }
    finally {
      sentinel.leaving(((BishopSentinel)sentinel).validMovement);
    }
  }
// ***** VDMTOOLS END Name=validMovement#2|Cell|Cell

}
;
