package mfes_shogi;

// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2013-12-08 by the VDM++ to JAVA Code Generator
// (v9.0.2 - Thu 14-Mar-2013 12:36:47 +0900)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// This file was genereted from "D:\\FEUP\\4o ano\\1o Semestre\\MFES\\MFES_SHOGI\\MFES_SHOGI\\classes/BoardState.rtf".

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO
import java.util.Map;
import java.util.Set;
import java.util.List;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import jp.vdmtools.VDM.UTIL;
import jp.vdmtools.VDM.Record;
import jp.vdmtools.VDM.Sentinel;
import jp.vdmtools.VDM.EvaluatePP;
import jp.vdmtools.VDM.CGException;
// ***** VDMTOOLS END Name=imports



public class BoardState implements EvaluatePP {

// ***** VDMTOOLS START Name=capturedPieces KEEP=NO
  private volatile Map capturedPieces = new HashMap();
// ***** VDMTOOLS END Name=capturedPieces

// ***** VDMTOOLS START Name=lines KEEP=NO
  public volatile Map lines = new HashMap();
// ***** VDMTOOLS END Name=lines

// ***** VDMTOOLS START Name=sentinel KEEP=NO
  volatile Sentinel sentinel;
// ***** VDMTOOLS END Name=sentinel


// ***** VDMTOOLS START Name=BoardStateSentinel KEEP=NO
  class BoardStateSentinel extends Sentinel {

    public final int vdm_equals = 0;

    public final int BoardState = 1;

    public final int linesEquals = 2;

    public final int capturedEquals = 3;

    public final int nr_functions = 4;


    public BoardStateSentinel () throws CGException {}


    public BoardStateSentinel (EvaluatePP instance) throws CGException {
      init(nr_functions, instance);
    }

  }
// ***** VDMTOOLS END Name=BoardStateSentinel
;

// ***** VDMTOOLS START Name=evaluatePP#1|int KEEP=NO
  public Boolean evaluatePP (int fnr) throws CGException {
    return Boolean.TRUE;
  }
// ***** VDMTOOLS END Name=evaluatePP#1|int


// ***** VDMTOOLS START Name=setSentinel KEEP=NO
  public void setSentinel () {
    try {
      sentinel = new BoardStateSentinel(this);
    }
    catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=setSentinel


// ***** VDMTOOLS START Name=vdm_init_BoardState KEEP=NO
  private void vdm_init_BoardState () {
    try {
      setSentinel();
    }
    catch (Exception e) {
      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=vdm_init_BoardState


// ***** VDMTOOLS START Name=inv_BoardState KEEP=NO
  public Boolean inv_BoardState () {
    Boolean rexpr_2 = null;
    Boolean var1_3 = null;
    if ((var1_3 = Boolean.valueOf(new HashSet(lines.keySet()).size() == 9)).booleanValue()) {
      Set var2_12 = new HashSet();
      var2_12 = new HashSet();
      for (int count_15 = 1; count_15 <= 9; count_15++) 
        var2_12.add(new Integer(count_15));
      var1_3 = Boolean.valueOf(UTIL.equals(new HashSet(lines.keySet()), var2_12));
    }
    if ((rexpr_2 = var1_3).booleanValue()) {
      boolean tmpQuant_19 = true;
      {
        Set e1_set_22 = new HashSet(capturedPieces.values());
        List seqp = null;
        Set tmpSet_49 = new HashSet(e1_set_22);
        for (Iterator enm_48 = tmpSet_49.iterator(); enm_48.hasNext() && tmpQuant_19; ) {
          List elem_47 = UTIL.ConvertToList(enm_48.next());
          /* seqp */
          seqp = elem_47;
          Boolean pred_23 = null;
          if ((pred_23 = Boolean.valueOf(seqp.size() == new HashSet(seqp).size())).booleanValue()) {
            boolean tmpQuant_31 = true;
            {
              Set e1_set_34 = new HashSet(seqp);
              Piece p = null;
              Set tmpSet_45 = new HashSet(e1_set_34);
              for (Iterator enm_44 = tmpSet_45.iterator(); enm_44.hasNext() && tmpQuant_31; ) {
                Piece elem_43 = (Piece)enm_44.next();
                /* p */
                p = elem_43;
                if (!UTIL.Contains(new HashSet(UTIL.ConvertToList(capturedPieces.get((p.belongTo)))), p)) 
                  tmpQuant_31 = false;
              }
            }
            pred_23 = Boolean.valueOf(tmpQuant_31);
          }
          if (!pred_23.booleanValue()) 
            tmpQuant_19 = false;
        }
      }
      rexpr_2 = Boolean.valueOf(tmpQuant_19);
    }
    return rexpr_2;
  }
// ***** VDMTOOLS END Name=inv_BoardState


// ***** VDMTOOLS START Name=BoardState KEEP=NO
  public BoardState () throws CGException {
    vdm_init_BoardState();
  }
// ***** VDMTOOLS END Name=BoardState


// ***** VDMTOOLS START Name=BoardState#2|List|Map KEEP=NO
  public BoardState (final List state, final Map captured) throws CGException {
    vdm_init_BoardState();
    {
      Map res_m_6 = new HashMap();
      {
        Set e_set_16 = new HashSet();
        e_set_16 = new HashSet();
        for (int count_19 = 1; count_19 <= 9; count_19++) 
          e_set_16.add(new Integer(count_19));
        Number y = null;
        Set tmpSet_25 = new HashSet(e_set_16);
        for (Iterator enm_24 = tmpSet_25.iterator(); enm_24.hasNext(); ) {
          Number elem_23 = UTIL.NumberToInt(enm_24.next());
          /* y */
          y = elem_23;
          List arg_9 = null;
          if ((1 > y.intValue()) || (y.intValue() > state.size())) 
            UTIL.RunTime("Illegal index");
          arg_9 = Board.mapStartSeq(UTIL.ConvertToList(state.get(y.intValue() - 1)), new Integer(1), y);
          res_m_6.put(y, new BoardLine(arg_9, y));
        }
      }
      final Map atom_1 = res_m_6;
      final Map atom_2 = new HashMap();
      lines = (Map)UTIL.clone(atom_1);
      Map rhs_30 = atom_2;
      if (!(((Object)rhs_30) instanceof Map)) 
        UTIL.RunTime("Incompatible type");
      capturedPieces = (Map)UTIL.clone(rhs_30);
    }
    Map rhs_31 = new HashMap();
    rhs_31 = new HashMap(capturedPieces);
    rhs_31.putAll(captured);
    capturedPieces = (Map)UTIL.clone(rhs_31);
  }
// ***** VDMTOOLS END Name=BoardState#2|List|Map


// ***** VDMTOOLS START Name=vdm_equals#1|Board KEEP=NO
  public Boolean vdm_equals (final Board b) throws CGException {
    sentinel.entering(((BoardStateSentinel)sentinel).vdm_equals);
    try {
      Boolean rexpr_2 = null;
      if ((rexpr_2 = linesEquals(b.getLines())).booleanValue()) 
        rexpr_2 = capturedEquals(b.getCapturedPieces());
      return rexpr_2;
    }
    finally {
      sentinel.leaving(((BoardStateSentinel)sentinel).vdm_equals);
    }
  }
// ***** VDMTOOLS END Name=vdm_equals#1|Board


// ***** VDMTOOLS START Name=linesEquals#1|Map KEEP=NO
  private Boolean linesEquals (final Map l) throws CGException {
    sentinel.entering(((BoardStateSentinel)sentinel).linesEquals);
    try {
      {
        Set iset_6 = new HashSet(l.keySet());
        Set tmpSet_114 = new HashSet(iset_6);
        for (Iterator enm_113 = tmpSet_114.iterator(); enm_113.hasNext(); ) {
          Number elem_2 = UTIL.NumberToInt(enm_113.next());
          Number y = null;
          /* y */
          y = elem_2;
          {
            Set iset_9 = new HashSet();
            iset_9 = new HashSet();
            for (int count_12 = 1; count_12 <= 9; count_12++) 
              iset_9.add(new Integer(count_12));
            Set iset_15 = iset_9;
            Set tmpSet_112 = new HashSet(iset_15);
            for (Iterator enm_111 = tmpSet_112.iterator(); enm_111.hasNext(); ) {
              Number elem_7 = UTIL.NumberToInt(enm_111.next());
              Number x = null;
              /* x */
              x = elem_7;
              Boolean cond_16 = null;
              Boolean var1_17 = null;
              BoardLine obj_24 = (BoardLine)l.get(y);
              if ((var1_17 = Boolean.valueOf(UTIL.equals((obj_24.getCell(x).piece), null))).booleanValue()) {
                BoardLine obj_33 = (BoardLine)lines.get(y);
                var1_17 = Boolean.valueOf(!UTIL.equals((obj_33.getCell(x).piece), null));
              }
              if (!(cond_16 = var1_17).booleanValue()) {
                Boolean var2_36 = null;
                BoardLine obj_43 = (BoardLine)l.get(y);
                if ((var2_36 = Boolean.valueOf(!UTIL.equals((obj_43.getCell(x).piece), null))).booleanValue()) {
                  BoardLine obj_52 = (BoardLine)lines.get(y);
                  var2_36 = Boolean.valueOf(UTIL.equals((obj_52.getCell(x).piece), null));
                }
                cond_16 = var2_36;
              }
              if (cond_16.booleanValue()) 
                return Boolean.FALSE;
              else {
                Boolean cond_55 = null;
                Boolean var1_56 = null;
                BoardLine obj_63 = (BoardLine)l.get(y);
                if ((var1_56 = Boolean.valueOf(!UTIL.equals((obj_63.getCell(x).piece), null))).booleanValue()) {
                  BoardLine obj_72 = (BoardLine)lines.get(y);
                  var1_56 = Boolean.valueOf(!UTIL.equals((obj_72.getCell(x).piece), null));
                }
                if ((cond_55 = var1_56).booleanValue()) {
                  Boolean var2_75 = null;
                  BoardLine obj_83 = (BoardLine)l.get(y);
                  BoardLine obj_90 = (BoardLine)lines.get(y);
                  if (!(var2_75 = Boolean.valueOf(!(obj_83.getCell(x).piece).getClass().equals((obj_90.getCell(x).piece).getClass()))).booleanValue()) {
                    BoardLine obj_99 = (BoardLine)l.get(y);
                    BoardLine obj_107 = (BoardLine)lines.get(y);
                    var2_75 = Boolean.valueOf(!UTIL.equals(((obj_99.getCell(x).piece).belongTo), ((obj_107.getCell(x).piece).belongTo)));
                  }
                  cond_55 = var2_75;
                }
                {
                  if (cond_55.booleanValue()) 
                    return Boolean.FALSE;
                }
              }
            }
          }
        }
      }
      return Boolean.TRUE;
    }
    finally {
      sentinel.leaving(((BoardStateSentinel)sentinel).linesEquals);
    }
  }
// ***** VDMTOOLS END Name=linesEquals#1|Map


// ***** VDMTOOLS START Name=capturedEquals#1|Map KEEP=NO
  private Boolean capturedEquals (final Map c) throws CGException {
    sentinel.entering(((BoardStateSentinel)sentinel).capturedEquals);
    try {
      {
        Set iset_6 = new HashSet(c.keySet());
        Set tmpSet_38 = new HashSet(iset_6);
        for (Iterator enm_37 = tmpSet_38.iterator(); enm_37.hasNext(); ) {
          Object elem_2 = enm_37.next();
          Object p = null;
          /* p */
          p = elem_2;
          if (!UTIL.Contains(new HashSet(capturedPieces.keySet()), p)) 
            return Boolean.FALSE;
          else {
            Set iset_17 = new HashSet(UTIL.ConvertToList(c.get(p)));
            Set tmpSet_35 = new HashSet(iset_17);
            for (Iterator enm_34 = tmpSet_35.iterator(); enm_34.hasNext(); ) {
              Piece elem_11 = (Piece)enm_34.next();
              Piece piece = null;
              /* piece */
              piece = elem_11;
              boolean tmpQuant_20 = false;
              {
                Set e1_set_25 = new HashSet(UTIL.ConvertToList(capturedPieces.get(p)));
                Piece pi = null;
                Set tmpSet_32 = new HashSet(e1_set_25);
                for (Iterator enm_31 = tmpSet_32.iterator(); enm_31.hasNext() && !tmpQuant_20; ) {
                  Piece elem_30 = (Piece)enm_31.next();
                  /* pi */
                  pi = elem_30;
                  if (pi.getClass().equals(piece.getClass())) 
                    tmpQuant_20 = true;
                }
              }
              if (!tmpQuant_20) 
                return Boolean.FALSE;
            }
          }
        }
      }
      return Boolean.TRUE;
    }
    finally {
      sentinel.leaving(((BoardStateSentinel)sentinel).capturedEquals);
    }
  }
// ***** VDMTOOLS END Name=capturedEquals#1|Map

}
;
