package mfes_shogi;

// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2013-12-08 by the VDM++ to JAVA Code Generator
// (v9.0.2 - Thu 14-Mar-2013 12:36:47 +0900)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// This file was genereted from "D:\\FEUP\\4o ano\\1o Semestre\\MFES\\MFES_SHOGI\\MFES_SHOGI\\classes/Cell.rtf".

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO
import java.util.Set;
import java.util.HashSet;
import jp.vdmtools.VDM.UTIL;
import jp.vdmtools.VDM.Record;
import jp.vdmtools.VDM.Sentinel;
import jp.vdmtools.VDM.EvaluatePP;
import jp.vdmtools.VDM.CGException;
// ***** VDMTOOLS END Name=imports



public class Cell implements EvaluatePP {

// ***** VDMTOOLS START Name=y KEEP=NO
  public volatile Number y = null;
// ***** VDMTOOLS END Name=y

// ***** VDMTOOLS START Name=x KEEP=NO
  public volatile Number x = null;
// ***** VDMTOOLS END Name=x

// ***** VDMTOOLS START Name=piece KEEP=NO
  public volatile Piece piece = null;
// ***** VDMTOOLS END Name=piece

// ***** VDMTOOLS START Name=sentinel KEEP=NO
  volatile Sentinel sentinel;
// ***** VDMTOOLS END Name=sentinel


// ***** VDMTOOLS START Name=CellSentinel KEEP=NO
  class CellSentinel extends Sentinel {

    public final int Cell__2_M_M = 0;

    public final int promotionZone = 1;

    public final int Cell__3_M_M_n_Piece = 2;

    public final int nr_functions = 3;


    public CellSentinel () throws CGException {}


    public CellSentinel (EvaluatePP instance) throws CGException {
      init(nr_functions, instance);
    }

  }
// ***** VDMTOOLS END Name=CellSentinel
;

// ***** VDMTOOLS START Name=evaluatePP#1|int KEEP=NO
  public Boolean evaluatePP (int fnr) throws CGException {
    return Boolean.TRUE;
  }
// ***** VDMTOOLS END Name=evaluatePP#1|int


// ***** VDMTOOLS START Name=setSentinel KEEP=NO
  public void setSentinel () {
    try {
      sentinel = new CellSentinel(this);
    }
    catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=setSentinel


// ***** VDMTOOLS START Name=vdm_init_Cell KEEP=NO
  private void vdm_init_Cell () {
    try {
      setSentinel();
    }
    catch (Exception e) {
      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=vdm_init_Cell


// ***** VDMTOOLS START Name=inv_Cell KEEP=NO
  public Boolean inv_Cell () {
    Boolean rexpr_2 = null;
    Set var2_5 = new HashSet();
    var2_5 = new HashSet();
    for (int count_8 = 1; count_8 <= 9; count_8++) 
      var2_5.add(new Integer(count_8));
    if ((rexpr_2 = Boolean.valueOf(UTIL.Contains(var2_5, x))).booleanValue()) {
      Set var2_13 = new HashSet();
      var2_13 = new HashSet();
      for (int count_16 = 1; count_16 <= 9; count_16++) 
        var2_13.add(new Integer(count_16));
      rexpr_2 = Boolean.valueOf(UTIL.Contains(var2_13, y));
    }
    return rexpr_2;
  }
// ***** VDMTOOLS END Name=inv_Cell


// ***** VDMTOOLS START Name=Cell KEEP=NO
  public Cell () throws CGException {
    vdm_init_Cell();
  }
// ***** VDMTOOLS END Name=Cell


// ***** VDMTOOLS START Name=Cell#2|Number|Number KEEP=NO
  public Cell (final Number xi, final Number yi) throws CGException {
    vdm_init_Cell();
    {
      final Number atom_1 = xi;
      final Number atom_2 = yi;
      x = UTIL.NumberToInt(UTIL.clone(atom_1));
      y = UTIL.NumberToInt(UTIL.clone(atom_2));
    }
    piece = null;
  }
// ***** VDMTOOLS END Name=Cell#2|Number|Number


// ***** VDMTOOLS START Name=Cell#3|Number|Number|Piece KEEP=NO
  public Cell (final Number xi, final Number yi, final Piece p) throws CGException {
    vdm_init_Cell();
    {
      final Number atom_1 = xi;
      final Number atom_2 = yi;
      x = UTIL.NumberToInt(UTIL.clone(atom_1));
      y = UTIL.NumberToInt(UTIL.clone(atom_2));
    }
    piece = (Piece)UTIL.clone(p);
  }
// ***** VDMTOOLS END Name=Cell#3|Number|Number|Piece


// ***** VDMTOOLS START Name=promotionZone#1|Object KEEP=NO
  public Boolean promotionZone (final Object p) throws CGException {
    sentinel.entering(((CellSentinel)sentinel).promotionZone);
    try {
      Boolean cond_2 = null;
      if ((cond_2 = Boolean.valueOf(UTIL.equals(p, new quotes.White()))).booleanValue()) 
        cond_2 = Boolean.valueOf(y.intValue() < 4);
      if (cond_2.booleanValue()) 
        return Boolean.TRUE;
      else {
        Boolean cond_10 = null;
        if ((cond_10 = Boolean.valueOf(UTIL.equals(p, new quotes.Black()))).booleanValue()) 
          cond_10 = Boolean.valueOf(y.intValue() > 6);
        if (cond_10.booleanValue()) 
          return Boolean.TRUE;
        else {
          return Boolean.FALSE;
        }
      }
    }
    finally {
      sentinel.leaving(((CellSentinel)sentinel).promotionZone);
    }
  }
// ***** VDMTOOLS END Name=promotionZone#1|Object

}
;
