package mfes_shogi;
//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2013-12-07 by the VDM++ to JAVA Code Generator
// (v9.0.2 - Thu 14-Mar-2013 12:36:47 +0900)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// This file was genereted from "C:\\Users\\vitor_000\\Documents\\Overture\\workspace\\MFES_SHOGI\\classes\\Lance.rtf".

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO
import java.util.Set;
import java.util.HashSet;
import java.util.Iterator;
import jp.vdmtools.VDM.UTIL;
import jp.vdmtools.VDM.Record;
import jp.vdmtools.VDM.Sentinel;
import jp.vdmtools.VDM.EvaluatePP;
import jp.vdmtools.VDM.CGException;
// ***** VDMTOOLS END Name=imports



public class Lance extends Piece {


// ***** VDMTOOLS START Name=LanceSentinel KEEP=NO
  class LanceSentinel extends PieceSentinel {

    public final int Lance = 10;

    public final int validMovement = 11;

    public final int nr_functions = 12;


    public LanceSentinel () throws CGException {}


    public LanceSentinel (EvaluatePP instance) throws CGException {
      init(nr_functions, instance);
    }

  }
// ***** VDMTOOLS END Name=LanceSentinel
;

// ***** VDMTOOLS START Name=setSentinel KEEP=NO
  public void setSentinel () {
    try {
      sentinel = new LanceSentinel(this);
    }
    catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=setSentinel


// ***** VDMTOOLS START Name=vdm_init_Lance KEEP=NO
  private void vdm_init_Lance () {}
// ***** VDMTOOLS END Name=vdm_init_Lance


// ***** VDMTOOLS START Name=Lance KEEP=NO
  public Lance () throws CGException {
    vdm_init_Lance();
  }
// ***** VDMTOOLS END Name=Lance


// ***** VDMTOOLS START Name=Lance#1|Object KEEP=NO
  public Lance (final Object p) throws CGException {
    super(p);
    vdm_init_Lance();
  }
// ***** VDMTOOLS END Name=Lance#1|Object


// ***** VDMTOOLS START Name=validMovement#2|Cell|Cell KEEP=NO
  public Boolean validMovement (final Cell c1, final Cell c2) throws CGException {
    sentinel.entering(((LanceSentinel)sentinel).validMovement);
    try {
      if (promoted.booleanValue()) 
        return validGoldGeneralMove(c1, c2);
      else {
        Boolean rexpr_4 = null;
        if ((rexpr_4 = Boolean.valueOf((c1.x).intValue() == (c2.x).intValue())).booleanValue()) {
          boolean tmpQuant_11 = false;
          {
            Set e_set_12 = new HashSet();
            e_set_12 = new HashSet();
            for (int count_15 = 1; count_15 <= 8; count_15++) 
              e_set_12.add(new Integer(count_15));
            Number y = null;
            Set tmpSet_102 = new HashSet(e_set_12);
            for (Iterator enm_101 = tmpSet_102.iterator(); enm_101.hasNext() && !tmpQuant_11; ) {
              Number elem_100 = UTIL.NumberToInt(enm_101.next());
              /* y */
              y = elem_100;
              Boolean pred_18 = null;
              Boolean var1_19 = null;
              Boolean var1_20 = null;
              if ((var1_20 = Boolean.valueOf((c1.y).intValue() == ((c2.y).intValue() + (y.intValue() * direction().intValue())))).booleanValue()) {
                boolean tmpQuant_31 = true;
                {
                  Set e_set_32 = new HashSet();
                  Set var1_33 = new HashSet();
                  var1_33 = new HashSet();
                  int lbi_47 = ((c2.y).intValue() + direction().intValue());
                  int ubi_48 = ((c2.y).intValue() + ((y.intValue() - 1) * direction().intValue()));
                  for (int count_46 = lbi_47; count_46 <= ubi_48; count_46++) 
                    var1_33.add(new Integer(count_46));
                  Set var2_49 = new HashSet();
                  var2_49 = new HashSet();
                  int lbi_63 = ((c2.y).intValue() + ((y.intValue() - 1) * direction().intValue()));
                  int ubi_64 = ((c2.y).intValue() + direction().intValue());
                  for (int count_62 = lbi_63; count_62 <= ubi_64; count_62++) 
                    var2_49.add(new Integer(count_62));
                  e_set_32 = new HashSet(var1_33);
                  e_set_32.addAll(var2_49);
                  Number yi = null;
                  Set tmpSet_91 = new HashSet(e_set_32);
                  for (Iterator enm_90 = tmpSet_91.iterator(); enm_90.hasNext() && tmpQuant_31; ) {
                    Number elem_89 = UTIL.NumberToInt(enm_90.next());
                    /* yi */
                    yi = elem_89;
                    Boolean pred_65 = null;
                    Boolean var1_66 = null;
                    Boolean var1_67 = null;
                    Board obj_72 = Board.getInstance();
                    if (!(var1_67 = Boolean.valueOf(UTIL.equals((obj_72.getCell((c1.x), yi).piece), null))).booleanValue()) 
                      var1_67 = Boolean.valueOf(yi.intValue() == y.intValue());
                    if (!(var1_66 = var1_67).booleanValue()) 
                      var1_66 = Boolean.valueOf(yi.intValue() == (c1.y).intValue());
                    if (!(pred_65 = var1_66).booleanValue()) 
                      pred_65 = Boolean.valueOf(yi.intValue() == (c2.y).intValue());
                    if (!pred_65.booleanValue()) 
                      tmpQuant_31 = false;
                  }
                }
                var1_20 = Boolean.valueOf(tmpQuant_31);
              }
              if ((var1_19 = var1_20).booleanValue()) 
                var1_19 = notFriend(c1, c2);
              if ((pred_18 = var1_19).booleanValue()) 
                pred_18 = Boolean.valueOf(!protectingKing(c1, c2).booleanValue());
              if (pred_18.booleanValue()) 
                tmpQuant_11 = true;
            }
          }
          rexpr_4 = Boolean.valueOf(tmpQuant_11);
        }
        return rexpr_4;
      }
    }
    finally {
      sentinel.leaving(((LanceSentinel)sentinel).validMovement);
    }
  }
// ***** VDMTOOLS END Name=validMovement#2|Cell|Cell

}
;
