package mfes_shogi;

//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2013-12-02 by the VDM++ to JAVA Code Generator
// (v9.0.2 - Thu 14-Mar-2013 12:36:47 +0900)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// This file was genereted from "D:\\FEUP\\4o ano\\1o Semestre\\MFES\\MFES_SHOGI\\MFES_SHOGI\\classes/Pawn.vdmpp".

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO
import jp.vdmtools.VDM.UTIL;
import jp.vdmtools.VDM.Record;
import jp.vdmtools.VDM.Sentinel;
import jp.vdmtools.VDM.EvaluatePP;
import jp.vdmtools.VDM.CGException;
// ***** VDMTOOLS END Name=imports



public class Pawn extends Piece {


// ***** VDMTOOLS START Name=PawnSentinel KEEP=NO
  class PawnSentinel extends PieceSentinel {

    public final int Pawn = 9;

    public final int validMovement = 10;

    public final int nr_functions = 11;


    public PawnSentinel () throws CGException {}


    public PawnSentinel (EvaluatePP instance) throws CGException {
      init(nr_functions, instance);
    }

  }
// ***** VDMTOOLS END Name=PawnSentinel
;

// ***** VDMTOOLS START Name=setSentinel KEEP=NO
  public void setSentinel () {
    try {
      sentinel = new PawnSentinel(this);
    }
    catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=setSentinel


// ***** VDMTOOLS START Name=vdm_init_Pawn KEEP=NO
  private void vdm_init_Pawn () {}
// ***** VDMTOOLS END Name=vdm_init_Pawn


// ***** VDMTOOLS START Name=Pawn KEEP=NO
  public Pawn () throws CGException {
    vdm_init_Pawn();
  }
// ***** VDMTOOLS END Name=Pawn


// ***** VDMTOOLS START Name=Pawn#1|Object KEEP=NO
  public Pawn (final Object p) throws CGException {
    super(p);
    vdm_init_Pawn();
  }
// ***** VDMTOOLS END Name=Pawn#1|Object


// ***** VDMTOOLS START Name=validMovement#2|Cell|Cell KEEP=NO
  public Boolean validMovement (final Cell c1, final Cell c2) throws CGException {
    sentinel.entering(((PawnSentinel)sentinel).validMovement);
    try {
      if (promoted.booleanValue()) 
        return validGoldGeneralMove(c1, c2);
      else {
        Boolean rexpr_4 = null;
        Boolean var1_5 = null;
        Boolean var1_6 = null;
        if ((var1_6 = Boolean.valueOf((c1.x).intValue() == (c2.x).intValue())).booleanValue()) 
          var1_6 = Boolean.valueOf((c1.y).intValue() == ((c2.y).intValue() + direction().intValue()));
        if ((var1_5 = var1_6).booleanValue()) {
          Boolean var2_19 = null;
          if (!(var2_19 = Boolean.valueOf(UTIL.equals((c2.piece), null))).booleanValue()) {
            Boolean var2_24 = null;
            if ((var2_24 = Boolean.valueOf(!UTIL.equals((c2.piece), null))).booleanValue()) 
              var2_24 = Boolean.valueOf(!UTIL.equals(((c2.piece).belongTo), ((c1.piece).belongTo)));
            var2_19 = var2_24;
          }
          var1_5 = var2_19;
        }
        if ((rexpr_4 = var1_5).booleanValue()) 
          rexpr_4 = Boolean.valueOf(!protectingKing(c1).booleanValue());
        return rexpr_4;
      }
    }
    finally {
      sentinel.leaving(((PawnSentinel)sentinel).validMovement);
    }
  }
// ***** VDMTOOLS END Name=validMovement#2|Cell|Cell
}
;
