package mfes_shogi;

// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2013-12-08 by the VDM++ to JAVA Code Generator
// (v9.0.2 - Thu 14-Mar-2013 12:36:47 +0900)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// This file was genereted from "D:\\FEUP\\4o ano\\1o Semestre\\MFES\\MFES_SHOGI\\MFES_SHOGI\\classes/Piece.rtf".

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO
import java.util.Set;
import java.util.HashSet;
import jp.vdmtools.VDM.UTIL;
import jp.vdmtools.VDM.Record;
import jp.vdmtools.VDM.Sentinel;
import jp.vdmtools.VDM.EvaluatePP;
import jp.vdmtools.VDM.CGException;
// ***** VDMTOOLS END Name=imports



public abstract class Piece implements EvaluatePP {

// ***** VDMTOOLS START Name=belongTo KEEP=NO
  public volatile Object belongTo = null;
// ***** VDMTOOLS END Name=belongTo

// ***** VDMTOOLS START Name=promoted KEEP=NO
  protected volatile Boolean promoted = null;
// ***** VDMTOOLS END Name=promoted

// ***** VDMTOOLS START Name=sentinel KEEP=NO
  volatile Sentinel sentinel;
// ***** VDMTOOLS END Name=sentinel


// ***** VDMTOOLS START Name=PieceSentinel KEEP=NO
  class PieceSentinel extends Sentinel {

    public final int Piece = 0;

    public final int capture = 1;

    public final int promote = 2;

    public final int direction = 3;

    public final int notFriend = 4;

    public final int getPromoted = 5;

    public final int validKingMove = 6;

    public final int validMovement = 7;

    public final int protectingKing = 8;

    public final int validGoldGeneralMove = 9;

    public final int nr_functions = 10;


    public PieceSentinel () throws CGException {}


    public PieceSentinel (EvaluatePP instance) throws CGException {
      init(nr_functions, instance);
    }

  }
// ***** VDMTOOLS END Name=PieceSentinel
;

// ***** VDMTOOLS START Name=evaluatePP#1|int KEEP=NO
  public Boolean evaluatePP (int fnr) throws CGException {
    return Boolean.TRUE;
  }
// ***** VDMTOOLS END Name=evaluatePP#1|int


// ***** VDMTOOLS START Name=setSentinel KEEP=NO
  public void setSentinel () {
    try {
      sentinel = new PieceSentinel(this);
    }
    catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=setSentinel


// ***** VDMTOOLS START Name=vdm_init_Piece KEEP=NO
  private void vdm_init_Piece () {
    try {
      setSentinel();
      promoted = Boolean.FALSE;
    }
    catch (Exception e) {
      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=vdm_init_Piece


// ***** VDMTOOLS START Name=Piece KEEP=NO
  public Piece () throws CGException {
    vdm_init_Piece();
  }
// ***** VDMTOOLS END Name=Piece


// ***** VDMTOOLS START Name=Piece#1|Object KEEP=NO
  protected Piece (final Object p) throws CGException {
    vdm_init_Piece();
    belongTo = UTIL.clone(p);
  }
// ***** VDMTOOLS END Name=Piece#1|Object


// ***** VDMTOOLS START Name=direction KEEP=NO
  protected Number direction () throws CGException {
    sentinel.entering(((PieceSentinel)sentinel).direction);
    try {
      if (UTIL.equals(belongTo, new quotes.White())) 
        return new Integer(-1);
      else 
        return new Integer(1);
    }
    finally {
      sentinel.leaving(((PieceSentinel)sentinel).direction);
    }
  }
// ***** VDMTOOLS END Name=direction


// ***** VDMTOOLS START Name=validMovement#2|Cell|Cell KEEP=NO
  abstract public Boolean validMovement (final Cell c1, final Cell c2) throws CGException ;
// ***** VDMTOOLS END Name=validMovement#2|Cell|Cell


// ***** VDMTOOLS START Name=pre_validMovement#2|Cell|Cell KEEP=NO
  public Boolean pre_validMovement (final Cell c1, final Cell c2) throws CGException {
    return Boolean.valueOf(!UTIL.equals((c1.piece), null));
  }
// ***** VDMTOOLS END Name=pre_validMovement#2|Cell|Cell


// ***** VDMTOOLS START Name=capture KEEP=NO
  public void capture () throws CGException {
    sentinel.entering(((PieceSentinel)sentinel).capture);
    try {
      if (UTIL.equals(belongTo, new quotes.White())) 
        belongTo = new quotes.Black();
      else 
        belongTo = new quotes.White();
      promoted = Boolean.FALSE;
    }
    finally {
      sentinel.leaving(((PieceSentinel)sentinel).capture);
    }
  }
// ***** VDMTOOLS END Name=capture


// ***** VDMTOOLS START Name=promote KEEP=NO
  public void promote () throws CGException {
    sentinel.entering(((PieceSentinel)sentinel).promote);
    try {
      if (!this.pre_promote().booleanValue()) 
        UTIL.RunTime("Precondition failure in promote");
      promoted = Boolean.TRUE;
    }
    finally {
      sentinel.leaving(((PieceSentinel)sentinel).promote);
    }
  }
// ***** VDMTOOLS END Name=promote


// ***** VDMTOOLS START Name=pre_promote KEEP=NO
  public Boolean pre_promote () throws CGException {
    Boolean varRes_1 = null;
    Boolean var1_2 = null;
    if ((var1_2 = Boolean.valueOf(!(this instanceof GoldGeneral))).booleanValue()) 
      var1_2 = Boolean.valueOf(!(this instanceof King));
    if ((varRes_1 = var1_2).booleanValue()) 
      varRes_1 = Boolean.valueOf(!promoted.booleanValue());
    return varRes_1;
  }
// ***** VDMTOOLS END Name=pre_promote


// ***** VDMTOOLS START Name=getPromoted KEEP=NO
  public Boolean getPromoted () throws CGException {
    sentinel.entering(((PieceSentinel)sentinel).getPromoted);
    try {
      return promoted;
    }
    finally {
      sentinel.leaving(((PieceSentinel)sentinel).getPromoted);
    }
  }
// ***** VDMTOOLS END Name=getPromoted


// ***** VDMTOOLS START Name=validGoldGeneralMove#2|Cell|Cell KEEP=NO
  protected Boolean validGoldGeneralMove (final Cell c1, final Cell c2) throws CGException {
    sentinel.entering(((PieceSentinel)sentinel).validGoldGeneralMove);
    try {
      if (!this.pre_validGoldGeneralMove(c1, c2).booleanValue()) 
        UTIL.RunTime("Precondition failure in validGoldGeneralMove");
      Boolean rexpr_3 = null;
      Boolean var1_4 = null;
      Boolean var1_5 = null;
      if ((var1_5 = Boolean.valueOf((c1.x).intValue() == (c2.x).intValue())).booleanValue()) 
        var1_5 = Boolean.valueOf(Math.abs(((c1.y).intValue() - (c2.y).intValue())) == 1);
      if (!(var1_4 = var1_5).booleanValue()) {
        Boolean var2_19 = null;
        if ((var2_19 = Boolean.valueOf((c1.y).intValue() == (c2.y).intValue())).booleanValue()) 
          var2_19 = Boolean.valueOf(Math.abs(((c1.x).intValue() - (c2.x).intValue())) == 1);
        var1_4 = var2_19;
      }
      if (!(rexpr_3 = var1_4).booleanValue()) {
        Boolean var2_33 = null;
        Boolean var1_34 = null;
        if ((var1_34 = Boolean.valueOf((c1.y).intValue() == ((c2.y).intValue() + direction().intValue()))).booleanValue()) 
          var1_34 = Boolean.valueOf(Math.abs(((c1.x).intValue() - (c2.x).intValue())) == 1);
        if ((var2_33 = var1_34).booleanValue()) 
          var2_33 = notFriend(c1, c2);
        rexpr_3 = var2_33;
      }
      return rexpr_3;
    }
    finally {
      sentinel.leaving(((PieceSentinel)sentinel).validGoldGeneralMove);
    }
  }
// ***** VDMTOOLS END Name=validGoldGeneralMove#2|Cell|Cell


// ***** VDMTOOLS START Name=pre_validGoldGeneralMove#2|Cell|Cell KEEP=NO
  protected Boolean pre_validGoldGeneralMove (final Cell c1, final Cell c2) throws CGException {
    return Boolean.valueOf(!UTIL.equals((c1.piece), null));
  }
// ***** VDMTOOLS END Name=pre_validGoldGeneralMove#2|Cell|Cell


// ***** VDMTOOLS START Name=validKingMove#2|Cell|Cell KEEP=NO
  protected Boolean validKingMove (final Cell c1, final Cell c2) throws CGException {
    sentinel.entering(((PieceSentinel)sentinel).validKingMove);
    try {
      if (!this.pre_validKingMove(c1, c2).booleanValue()) 
        UTIL.RunTime("Precondition failure in validKingMove");
      Boolean rexpr_3 = null;
      Boolean var1_4 = null;
      Boolean var1_5 = null;
      if ((var1_5 = Boolean.valueOf(Math.abs(((c1.x).intValue() - (c2.x).intValue())) == 0)).booleanValue()) 
        var1_5 = Boolean.valueOf(Math.abs(((c1.y).intValue() - (c2.y).intValue())) == 1);
      if (!(var1_4 = var1_5).booleanValue()) {
        Boolean var2_22 = null;
        if ((var2_22 = Boolean.valueOf(Math.abs(((c1.x).intValue() - (c2.x).intValue())) == 1)).booleanValue()) 
          var2_22 = Boolean.valueOf(Math.abs(((c1.y).intValue() - (c2.y).intValue())) == 0);
        var1_4 = var2_22;
      }
      if (!(rexpr_3 = var1_4).booleanValue()) {
        Boolean var2_39 = null;
        Boolean var1_40 = null;
        if ((var1_40 = Boolean.valueOf(Math.abs(((c1.x).intValue() - (c2.x).intValue())) == 1)).booleanValue()) 
          var1_40 = Boolean.valueOf(Math.abs(((c1.y).intValue() - (c2.y).intValue())) == 1);
        if ((var2_39 = var1_40).booleanValue()) 
          var2_39 = notFriend(c1, c2);
        rexpr_3 = var2_39;
      }
      return rexpr_3;
    }
    finally {
      sentinel.leaving(((PieceSentinel)sentinel).validKingMove);
    }
  }
// ***** VDMTOOLS END Name=validKingMove#2|Cell|Cell


// ***** VDMTOOLS START Name=pre_validKingMove#2|Cell|Cell KEEP=NO
  protected Boolean pre_validKingMove (final Cell c1, final Cell c2) throws CGException {
    return Boolean.valueOf(!UTIL.equals((c1.piece), null));
  }
// ***** VDMTOOLS END Name=pre_validKingMove#2|Cell|Cell


// ***** VDMTOOLS START Name=protectingKing#2|Cell|Cell KEEP=NO
  protected Boolean protectingKing (final Cell c1, final Cell c2) throws CGException {
    sentinel.entering(((PieceSentinel)sentinel).protectingKing);
    try {
      if (!this.pre_protectingKing(c1, c2).booleanValue()) 
        UTIL.RunTime("Precondition failure in protectingKing");
      {
        Boolean ret = null;
        Piece aux = null;
        aux = (Piece)UTIL.clone((c2.piece));
        c2.piece = (Piece)c1.piece;
        c1.piece = null;
        Board obj_12 = Board.getInstance();
        ret = (Boolean)UTIL.clone(obj_12.check(belongTo));
        c1.piece = (Piece)c2.piece;
        c2.piece = (Piece)aux;
        return ret;
      }
    }
    finally {
      sentinel.leaving(((PieceSentinel)sentinel).protectingKing);
    }
  }
// ***** VDMTOOLS END Name=protectingKing#2|Cell|Cell


// ***** VDMTOOLS START Name=pre_protectingKing#2|Cell|Cell KEEP=NO
  protected Boolean pre_protectingKing (final Cell c1, final Cell c2) throws CGException {
    return Boolean.valueOf(UTIL.equals((c1.piece), this));
  }
// ***** VDMTOOLS END Name=pre_protectingKing#2|Cell|Cell


// ***** VDMTOOLS START Name=notFriend#2|Cell|Cell KEEP=NO
  protected Boolean notFriend (final Cell c1, final Cell c2) throws CGException {
    sentinel.entering(((PieceSentinel)sentinel).notFriend);
    try {
      Boolean rexpr_3 = null;
      if (!(rexpr_3 = Boolean.valueOf(UTIL.equals((c2.piece), null))).booleanValue()) {
        Boolean var2_8 = null;
        if ((var2_8 = Boolean.valueOf(!UTIL.equals((c2.piece), null))).booleanValue()) 
          var2_8 = Boolean.valueOf(!UTIL.equals(((c2.piece).belongTo), ((c1.piece).belongTo)));
        rexpr_3 = var2_8;
      }
      return rexpr_3;
    }
    finally {
      sentinel.leaving(((PieceSentinel)sentinel).notFriend);
    }
  }
// ***** VDMTOOLS END Name=notFriend#2|Cell|Cell


// ***** VDMTOOLS START Name=intermediateVals#2|Number|Number KEEP=NO
  public Set intermediateVals (final Number x1, final Number x2) throws CGException {
    Set varRes_3 = new HashSet();
    if (x1.intValue() == x2.intValue()) 
      varRes_3 = new HashSet();
    else {
      Set var1_8 = new HashSet();
      var1_8 = new HashSet();
      Number lb_31 = new Double(x1.intValue() + ((double)(x2.intValue() - x1.intValue()) / (double)Math.abs((x2.intValue() - x1.intValue()))));
      if (!UTIL.IsInteger(lb_31)) 
        UTIL.RunTime("Lower bound was not an integer in set range expression");
      int lbi_30 = UTIL.NumberToInt(lb_31).intValue();
      Number ub_33 = new Double(x2.intValue() + ((double)(x1.intValue() - x2.intValue()) / (double)Math.abs((x1.intValue() - x2.intValue()))));
      if (!UTIL.IsInteger(ub_33)) 
        UTIL.RunTime("Upper bound was not an integer in set range expression");
      int ubi_32 = UTIL.NumberToInt(ub_33).intValue();
      for (int count_29 = lbi_30; count_29 <= ubi_32; count_29++) 
        var1_8.add(new Integer(count_29));
      Set var2_34 = new HashSet();
      var2_34 = new HashSet();
      Number lb_57 = new Double(x2.intValue() + ((double)(x1.intValue() - x2.intValue()) / (double)Math.abs((x1.intValue() - x2.intValue()))));
      if (!UTIL.IsInteger(lb_57)) 
        UTIL.RunTime("Lower bound was not an integer in set range expression");
      int lbi_56 = UTIL.NumberToInt(lb_57).intValue();
      Number ub_59 = new Double(x1.intValue() + ((double)(x2.intValue() - x1.intValue()) / (double)Math.abs((x2.intValue() - x1.intValue()))));
      if (!UTIL.IsInteger(ub_59)) 
        UTIL.RunTime("Upper bound was not an integer in set range expression");
      int ubi_58 = UTIL.NumberToInt(ub_59).intValue();
      for (int count_55 = lbi_56; count_55 <= ubi_58; count_55++) 
        var2_34.add(new Integer(count_55));
      varRes_3 = new HashSet(var1_8);
      varRes_3.addAll(var2_34);
    }
    return varRes_3;
  }
// ***** VDMTOOLS END Name=intermediateVals#2|Number|Number

}
;
